/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *hpaned1;
  GtkWidget *vbox1;
  GtkWidget *scrolledwindow2;
  GtkWidget *clist2;
  GtkWidget *label7;
  GtkWidget *button1;
  GtkWidget *button3;
  GtkWidget *button4;
  GtkWidget *button2;
  GtkWidget *notebook1;
  GtkWidget *vpaned1;
  GtkWidget *scrolledwindow1;
  GtkWidget *clist1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *scrolledwindow3;
  GtkWidget *clist3;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label13;
  GtkWidget *vpaned3;
  GtkWidget *scrolledwindow5;
  GtkWidget *clist5;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *hbox2;
  GtkWidget *label14;
  GtkWidget *scrolledwindow6;
  GtkWidget *clist6;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label20;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window1), "window1", window1);
  gtk_window_set_title (GTK_WINDOW (window1), _("FFSS Client - 0.01"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window1), 700, 400);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_ref (hpaned1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hpaned1", hpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hpaned1);
  gtk_container_add (GTK_CONTAINER (window1), hpaned1);
  gtk_paned_set_position (GTK_PANED (hpaned1), 80);

  vbox1 = gtk_vbox_new (FALSE, 30);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_paned_pack1 (GTK_PANED (hpaned1), vbox1, FALSE, TRUE);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 6);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  clist2 = gtk_clist_new (1);
  gtk_widget_ref (clist2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "clist2", clist2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), clist2);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 0, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (clist2));

  label7 = gtk_label_new (_("label7"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 0, label7);

  button1 = gtk_button_new_with_label (_("Rescan"));
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (vbox1), button1, FALSE, FALSE, 0);

  button3 = gtk_button_new_with_label (_("Shares"));
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_box_pack_start (GTK_BOX (vbox1), button3, FALSE, FALSE, 0);

  button4 = gtk_button_new_with_label (_("Connect"));
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  gtk_box_pack_start (GTK_BOX (vbox1), button4, FALSE, FALSE, 0);

  button2 = gtk_button_new_with_label (_("Search"));
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  gtk_box_pack_start (GTK_BOX (vbox1), button2, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), notebook1, TRUE, TRUE);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook1), GTK_POS_BOTTOM);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vpaned1", vpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned1);
  gtk_container_add (GTK_CONTAINER (notebook1), vpaned1);
  gtk_paned_set_position (GTK_PANED (vpaned1), 260);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_paned_pack1 (GTK_PANED (vpaned1), scrolledwindow1, FALSE, TRUE);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow1), 6);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  clist1 = gtk_clist_new (6);
  gtk_widget_ref (clist1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "clist1", clist1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), clist1);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 86);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 122);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 2, 55);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 3, 94);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 4, 74);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 5, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  label1 = gtk_label_new (_("Name"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label1);

  label2 = gtk_label_new (_("Comment"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, label2);

  label3 = gtk_label_new (_("State"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 2, label3);

  label4 = gtk_label_new (_("IP"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 3, label4);

  label5 = gtk_label_new (_("OS"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 4, label5);

  label6 = gtk_label_new (_("Domain"));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 5, label6);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_paned_pack2 (GTK_PANED (vpaned1), scrolledwindow3, TRUE, TRUE);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow3), 6);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist3 = gtk_clist_new (2);
  gtk_widget_ref (clist3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "clist3", clist3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), clist3);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 0, 129);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 1, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist3));

  label8 = gtk_label_new (_("Name"));
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 0, label8);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_LEFT);

  label9 = gtk_label_new (_("Comment"));
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 1, label9);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);

  label13 = gtk_label_new (_("Hosts"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label13);

  vpaned3 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vpaned3", vpaned3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned3);
  gtk_container_add (GTK_CONTAINER (notebook1), vpaned3);
  gtk_paned_set_position (GTK_PANED (vpaned3), 320);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow5);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow5", scrolledwindow5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow5);
  gtk_paned_pack1 (GTK_PANED (vpaned3), scrolledwindow5, FALSE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist5 = gtk_clist_new (5);
  gtk_widget_ref (clist5);
  gtk_object_set_data_full (GTK_OBJECT (window1), "clist5", clist5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist5);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), clist5);
  gtk_clist_set_column_width (GTK_CLIST (clist5), 0, 96);
  gtk_clist_set_column_width (GTK_CLIST (clist5), 1, 141);
  gtk_clist_set_column_width (GTK_CLIST (clist5), 2, 156);
  gtk_clist_set_column_width (GTK_CLIST (clist5), 3, 96);
  gtk_clist_set_column_width (GTK_CLIST (clist5), 4, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist5));

  label15 = gtk_label_new (_("Host/Share"));
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_clist_set_column_widget (GTK_CLIST (clist5), 0, label15);

  label16 = gtk_label_new (_("Remote Path"));
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_clist_set_column_widget (GTK_CLIST (clist5), 1, label16);

  label17 = gtk_label_new (_("Local Path"));
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_clist_set_column_widget (GTK_CLIST (clist5), 2, label17);

  label18 = gtk_label_new (_("File Size"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_clist_set_column_widget (GTK_CLIST (clist5), 3, label18);

  label19 = gtk_label_new (_("Position"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_clist_set_column_widget (GTK_CLIST (clist5), 4, label19);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_paned_pack2 (GTK_PANED (vpaned3), hbox2, TRUE, TRUE);

  label14 = gtk_label_new (_("Downloads"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label14);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow6);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow6", scrolledwindow6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow6);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow6);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow6), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist6 = gtk_clist_new (5);
  gtk_widget_ref (clist6);
  gtk_object_set_data_full (GTK_OBJECT (window1), "clist6", clist6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist6);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), clist6);
  gtk_clist_set_column_width (GTK_CLIST (clist6), 0, 96);
  gtk_clist_set_column_width (GTK_CLIST (clist6), 1, 127);
  gtk_clist_set_column_width (GTK_CLIST (clist6), 2, 118);
  gtk_clist_set_column_width (GTK_CLIST (clist6), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist6), 4, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist6));

  label24 = gtk_label_new (_("Host/Share"));
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_clist_set_column_widget (GTK_CLIST (clist6), 0, label24);

  label25 = gtk_label_new (_("Remote Path"));
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_clist_set_column_widget (GTK_CLIST (clist6), 1, label25);

  label26 = gtk_label_new (_("Local Path"));
  gtk_widget_ref (label26);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label26", label26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label26);
  gtk_clist_set_column_widget (GTK_CLIST (clist6), 2, label26);

  label27 = gtk_label_new (_("File Size"));
  gtk_widget_ref (label27);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label27", label27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label27);
  gtk_clist_set_column_widget (GTK_CLIST (clist6), 3, label27);

  label28 = gtk_label_new (_("Error"));
  gtk_widget_ref (label28);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label28", label28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label28);
  gtk_clist_set_column_widget (GTK_CLIST (clist6), 4, label28);

  label20 = gtk_label_new (_("Failures"));
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label20);

  gtk_signal_connect (GTK_OBJECT (window1), "delete_event",
                      GTK_SIGNAL_FUNC (on_window1_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist2), "button_press_event",
                      GTK_SIGNAL_FUNC (on_clist2_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_rescan_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (on_button3_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (on_button4_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (on_button2_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist1), "button_press_event",
                      GTK_SIGNAL_FUNC (on_clist1_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist1), "unselect_row",
                      GTK_SIGNAL_FUNC (on_clist1_unselect_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist3), "button_press_event",
                      GTK_SIGNAL_FUNC (on_clist3_button_press_event),
                      NULL);

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *vpaned2;
  GtkWidget *scrolledwindow4;
  GtkWidget *clist4;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *vbox2;
  GtkWidget *hbox1;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *statusbar1;

  window2 = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_object_set_data (GTK_OBJECT (window2), "window2", window2);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));
  gtk_window_set_position (GTK_WINDOW (window2), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window2), 500, 365);

  vpaned2 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned2);
  gtk_object_set_data_full (GTK_OBJECT (window2), "vpaned2", vpaned2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned2);
  gtk_container_add (GTK_CONTAINER (window2), vpaned2);
  gtk_paned_set_position (GTK_PANED (vpaned2), 300);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (window2), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_paned_pack1 (GTK_PANED (vpaned2), scrolledwindow4, FALSE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist4 = gtk_clist_new (3);
  gtk_widget_ref (clist4);
  gtk_object_set_data_full (GTK_OBJECT (window2), "clist4", clist4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), clist4);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 0, 45);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 1, 316);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 2, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist4));

  label10 = gtk_label_new (_("Type"));
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (window2), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 0, label10);

  label11 = gtk_label_new (_("Name"));
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (window2), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 1, label11);

  label12 = gtk_label_new (_("Size"));
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (window2), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 2, label12);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (window2), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_paned_pack2 (GTK_PANED (vpaned2), vbox2, TRUE, TRUE);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (window2), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 6);

  button5 = gtk_button_new_with_label (_("Download"));
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (window2), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);
  gtk_box_pack_start (GTK_BOX (hbox1), button5, FALSE, FALSE, 0);
  gtk_widget_set_usize (button5, 70, 20);

  button6 = gtk_button_new_with_label (_("Close"));
  gtk_widget_ref (button6);
  gtk_object_set_data_full (GTK_OBJECT (window2), "button6", button6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button6);
  gtk_box_pack_start (GTK_BOX (hbox1), button6, FALSE, FALSE, 0);
  gtk_widget_set_usize (button6, 70, 20);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_ref (statusbar1);
  gtk_object_set_data_full (GTK_OBJECT (window2), "statusbar1", statusbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox2), statusbar1, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (window2), "delete_event",
                      GTK_SIGNAL_FUNC (on_window2_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist4), "button_press_event",
                      GTK_SIGNAL_FUNC (on_clist4_button_press_event),
                      (gpointer)window2);
  gtk_signal_connect (GTK_OBJECT (button5), "clicked",
                      GTK_SIGNAL_FUNC (on_button5_clicked),
                      (gpointer)window2);
  gtk_signal_connect (GTK_OBJECT (button6), "clicked",
                      GTK_SIGNAL_FUNC (on_button6_clicked),
                      (gpointer)window2);

  return window2;
}

GtkWidget*
create_fileselection1 (void)
{
  GtkWidget *fileselection1;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;

  fileselection1 = gtk_file_selection_new (_("Save file as..."));
  gtk_object_set_data (GTK_OBJECT (fileselection1), "fileselection1", fileselection1);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection1), 10);
  gtk_window_set_position (GTK_WINDOW (fileselection1), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (fileselection1), TRUE);

  ok_button1 = GTK_FILE_SELECTION (fileselection1)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection1), "ok_button1", ok_button1);
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_FILE_SELECTION (fileselection1)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection1), "cancel_button1", cancel_button1);
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (ok_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button1_clicked),
                      (gpointer)fileselection1);
  gtk_signal_connect (GTK_OBJECT (cancel_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button1_clicked),
                      (gpointer)fileselection1);

  return fileselection1;
}

GtkWidget*
create_fileselection2 (void)
{
  GtkWidget *fileselection2;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;

  fileselection2 = gtk_file_selection_new (_("Save directory as ..."));
  gtk_object_set_data (GTK_OBJECT (fileselection2), "fileselection2", fileselection2);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection2), 10);
  gtk_window_set_position (GTK_WINDOW (fileselection2), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (fileselection2), TRUE);

  ok_button2 = GTK_FILE_SELECTION (fileselection2)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection2), "ok_button2", ok_button2);
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);

  cancel_button2 = GTK_FILE_SELECTION (fileselection2)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection2), "cancel_button2", cancel_button2);
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (ok_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button2_clicked),
                      (gpointer)fileselection2);
  gtk_signal_connect (GTK_OBJECT (cancel_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button2_clicked),
                      (gpointer)fileselection2);

  return fileselection2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *vbox3;
  GtkWidget *label29;
  GtkWidget *hbox3;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *button9;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window3), "window3", window3);
  gtk_widget_set_usize (window3, 400, 200);
  gtk_window_set_title (GTK_WINDOW (window3), _("Different file size... what should I do ?"));
  gtk_window_set_position (GTK_WINDOW (window3), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (window3), TRUE);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (window3), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (window3), vbox3);

  label29 = gtk_label_new ("");
  gtk_widget_ref (label29);
  gtk_object_set_data_full (GTK_OBJECT (window3), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (vbox3), label29, FALSE, FALSE, 0);
  gtk_widget_set_usize (label29, -2, 150);
  gtk_label_set_line_wrap (GTK_LABEL (label29), TRUE);

  hbox3 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (window3), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox3), 12);

  button7 = gtk_button_new_with_label (_("Resume"));
  gtk_widget_ref (button7);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button7", button7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button7);
  gtk_box_pack_start (GTK_BOX (hbox3), button7, FALSE, FALSE, 0);
  gtk_widget_set_usize (button7, 70, -2);

  button8 = gtk_button_new_with_label (_("Overwrite"));
  gtk_widget_ref (button8);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button8", button8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button8);
  gtk_box_pack_start (GTK_BOX (hbox3), button8, FALSE, FALSE, 0);
  gtk_widget_set_usize (button8, 70, -2);

  button9 = gtk_button_new_with_label (_("Ignore"));
  gtk_widget_ref (button9);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button9", button9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button9);
  gtk_box_pack_start (GTK_BOX (hbox3), button9, FALSE, FALSE, 0);
  gtk_widget_set_usize (button9, 70, -2);

  gtk_signal_connect (GTK_OBJECT (button7), "clicked",
                      GTK_SIGNAL_FUNC (on_button7_clicked),
                      (gpointer)window3);
  gtk_signal_connect (GTK_OBJECT (button8), "clicked",
                      GTK_SIGNAL_FUNC (on_button8_clicked),
                      (gpointer)window3);
  gtk_signal_connect (GTK_OBJECT (button9), "clicked",
                      GTK_SIGNAL_FUNC (on_button9_clicked),
                      (gpointer)window3);

  return window3;
}

