/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
//#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *hpaned1;
  GtkWidget *vbox1;
  GtkWidget *scrolledwindow2;
  GtkWidget *button1;
  GtkWidget *button3;
  GtkWidget *button4;
  GtkWidget *button2;
  GtkWidget *notebook1;
  GtkWidget *vpaned1;
  GtkWidget *scrolledwindow1;
  GtkWidget *scrolledwindow3;
  GtkWidget *label13;
  GtkWidget *vpaned3;
  GtkWidget *scrolledwindow5;
  GtkWidget *hbox2;
  GtkWidget *label14;
  GtkWidget *scrolledwindow6;
  GtkWidget *label20;
  GtkWidget *list1;
  GtkListStore *store1;
  GtkCellRenderer *renderer;
  GtkTreeViewColumn *column;
  GtkTreeSelection *select;
  GtkWidget *list2;
  GtkListStore *store2;
  GtkWidget *list3;
  GtkListStore *store3;
  GtkWidget *list4;
  GtkListStore *store4;
  GtkWidget *list5;
  GtkListStore *store5;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window1), "window1", window1);
  gtk_window_set_title (GTK_WINDOW (window1), _("FFSS Client Gtk - 0.02"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window1), 700, 400);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_ref (hpaned1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hpaned1", hpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hpaned1);
  gtk_container_add (GTK_CONTAINER (window1), hpaned1);
  gtk_paned_set_position (GTK_PANED (hpaned1), 80);

  vbox1 = gtk_vbox_new (FALSE, 30);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_paned_pack1 (GTK_PANED (hpaned1), vbox1, FALSE, TRUE);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 6);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
/**********/
  store1 = gtk_list_store_new(1,G_TYPE_STRING);
  gtk_object_set_data_full(GTK_OBJECT (window1),"store1",store1,NULL);
  list1 = gtk_tree_view_new_with_model(GTK_TREE_MODEL(store1));
  select = gtk_tree_view_get_selection(GTK_TREE_VIEW(list1));
  gtk_tree_selection_set_mode(select,GTK_SELECTION_SINGLE);
  g_signal_connect(G_OBJECT(select),"changed",G_CALLBACK(on_list1_selection_changed),NULL);

  renderer = gtk_cell_renderer_text_new();
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list1),0,"Domains",renderer,"text",0,NULL);

  gtk_widget_ref(list1);
  gtk_object_set_data_full(GTK_OBJECT(window1),"list1",list1,(GtkDestroyNotify)gtk_widget_unref);
  gtk_widget_show(list1);
  gtk_container_add(GTK_CONTAINER(scrolledwindow2),list1);
/**********/
  button1 = gtk_button_new_with_label (_("Rescan"));
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (vbox1), button1, FALSE, FALSE, 0);

  button3 = gtk_button_new_with_label (_("Shares"));
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_box_pack_start (GTK_BOX (vbox1), button3, FALSE, FALSE, 0);

  button4 = gtk_button_new_with_label (_("Connect"));
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  gtk_box_pack_start (GTK_BOX (vbox1), button4, FALSE, FALSE, 0);

  button2 = gtk_button_new_with_label (_("Search"));
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  gtk_box_pack_start (GTK_BOX (vbox1), button2, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), notebook1, TRUE, TRUE);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook1), GTK_POS_BOTTOM);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vpaned1", vpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned1);
  gtk_container_add (GTK_CONTAINER (notebook1), vpaned1);
  gtk_paned_set_position (GTK_PANED (vpaned1), 280);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_paned_pack1 (GTK_PANED (vpaned1), scrolledwindow1, TRUE, TRUE);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow1), 6);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
/**********/
  store2 = gtk_list_store_new(6,G_TYPE_STRING,G_TYPE_STRING,G_TYPE_STRING,G_TYPE_STRING,G_TYPE_STRING,G_TYPE_STRING);
  gtk_object_set_data_full(GTK_OBJECT (window1),"store2",store2,NULL);
  list2 = gtk_tree_view_new_with_model(GTK_TREE_MODEL(store2));
  select = gtk_tree_view_get_selection(GTK_TREE_VIEW(list2));
  gtk_tree_selection_set_mode(select,GTK_SELECTION_SINGLE);
  g_signal_connect(G_OBJECT(select),"changed",G_CALLBACK(on_list2_selection_changed),NULL);

  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list2),0,"Name",renderer,"text",0,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list2),1,"Comment",renderer,"text",1,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list2),2,"State",renderer,"text",2,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list2),3,"IP",renderer,"text",3,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list2),4,"OS",renderer,"text",4,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list2),5,"Domain",renderer,"text",5,NULL);
  gtk_tree_view_set_headers_clickable(GTK_TREE_VIEW(list2),TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list2),0);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,100);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list2),1);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,140);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list2),2);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,50);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list2),3);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,110);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list2),4);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,74);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list2),5);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,80);
  gtk_tree_view_column_set_resizable(column,TRUE);

  gtk_widget_ref(list2);
  gtk_object_set_data_full(GTK_OBJECT(window1),"list2",list2,(GtkDestroyNotify)gtk_widget_unref);
  gtk_widget_show(list2);
  gtk_container_add(GTK_CONTAINER(scrolledwindow1),list2);
/**********/
  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_paned_pack2 (GTK_PANED (vpaned1), scrolledwindow3, FALSE, TRUE);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow3), 6);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
/**********/
  store3 = gtk_list_store_new(2,G_TYPE_STRING,G_TYPE_STRING);
  gtk_object_set_data_full(GTK_OBJECT (window1),"store3",store3,NULL);
  list3 = gtk_tree_view_new_with_model(GTK_TREE_MODEL(store3));

  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list3),0,"Name",renderer,"text",0,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list3),1,"Comment",renderer,"text",1,NULL);
  gtk_tree_view_set_headers_clickable(GTK_TREE_VIEW(list3),TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list3),0);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,129);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list3),1);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,80);
  gtk_tree_view_column_set_resizable(column,TRUE);

  gtk_widget_ref(list3);
  gtk_object_set_data_full(GTK_OBJECT(window1),"list3",list3,(GtkDestroyNotify)gtk_widget_unref);
  gtk_widget_show(list3);
  gtk_container_add(GTK_CONTAINER(scrolledwindow3),list3);
/**********/
  label13 = gtk_label_new (_("Hosts"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label13);

  vpaned3 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vpaned3", vpaned3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned3);
  gtk_container_add (GTK_CONTAINER (notebook1), vpaned3);
  gtk_paned_set_position (GTK_PANED (vpaned3), 320);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow5);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow5", scrolledwindow5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow5);
  gtk_paned_pack1 (GTK_PANED (vpaned3), scrolledwindow5, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
/**********/
  store4 = gtk_list_store_new(6,G_TYPE_STRING,G_TYPE_STRING,G_TYPE_STRING,G_TYPE_STRING,G_TYPE_STRING,G_TYPE_POINTER);
  gtk_object_set_data_full(GTK_OBJECT (window1),"store4",store4,NULL);
  list4 = gtk_tree_view_new_with_model(GTK_TREE_MODEL(store4));

  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list4),0,"Host/Share",renderer,"text",0,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list4),1,"Remote Path",renderer,"text",1,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list4),2,"Local Path",renderer,"text",2,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list4),3,"File Size",renderer,"text",3,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list4),4,"Position",renderer,"text",4,NULL);
  gtk_tree_view_set_headers_clickable(GTK_TREE_VIEW(list4),TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list4),0);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,96);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list4),1);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,141);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list4),2);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,156);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list4),3);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,96);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list4),4);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,80);
  gtk_tree_view_column_set_resizable(column,TRUE);

  gtk_widget_ref(list4);
  gtk_object_set_data_full(GTK_OBJECT(window1),"list4",list4,(GtkDestroyNotify)gtk_widget_unref);
  gtk_widget_show(list4);
  gtk_container_add(GTK_CONTAINER(scrolledwindow5),list4);
/**********/
  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_paned_pack2 (GTK_PANED (vpaned3), hbox2, FALSE, TRUE);

  label14 = gtk_label_new (_("Downloads"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label14);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow6);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow6", scrolledwindow6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow6);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow6);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow6), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
/**********/
  store5 = gtk_list_store_new(5,G_TYPE_STRING,G_TYPE_STRING,G_TYPE_STRING,G_TYPE_STRING,G_TYPE_STRING);
  gtk_object_set_data_full(GTK_OBJECT (window1),"store5",store5,NULL);
  list5 = gtk_tree_view_new_with_model(GTK_TREE_MODEL(store5));

  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list5),0,"Host/Share",renderer,"text",0,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list5),1,"Remote Path",renderer,"text",1,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list5),2,"Local Path",renderer,"text",2,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list5),3,"File Size",renderer,"text",3,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list5),4,"Error",renderer,"text",4,NULL);
  gtk_tree_view_set_headers_clickable(GTK_TREE_VIEW(list5),TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list5),0);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,96);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list5),1);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,127);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list5),2);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,118);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list5),3);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,80);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list5),4);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,80);
  gtk_tree_view_column_set_resizable(column,TRUE);

  gtk_widget_ref(list5);
  gtk_object_set_data_full(GTK_OBJECT(window1),"list5",list5,(GtkDestroyNotify)gtk_widget_unref);
  gtk_widget_show(list5);
  gtk_container_add(GTK_CONTAINER(scrolledwindow6),list5);
/**********/
  label20 = gtk_label_new (_("Failures"));
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label20);

  gtk_signal_connect (GTK_OBJECT (window1), "delete_event",
                      GTK_SIGNAL_FUNC (on_window1_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_rescan_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (on_button3_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (on_button4_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (on_button2_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (list3), "button_press_event",
                      GTK_SIGNAL_FUNC (on_list3_button_press_event),
                      NULL);

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *vpaned2;
  GtkWidget *scrolledwindow4;
  GtkWidget *list1;
  GtkListStore *store1;
  GtkCellRenderer *renderer;
  GtkTreeViewColumn *column;
  GtkTreeSelection *select;
  GtkWidget *vbox2;
  GtkWidget *hbox1;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *statusbar1;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window2), "window2", window2);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));
  gtk_window_set_position (GTK_WINDOW (window2), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window2), 500, 365);

  vpaned2 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned2);
  gtk_object_set_data_full (GTK_OBJECT (window2), "vpaned2", vpaned2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned2);
  gtk_container_add (GTK_CONTAINER (window2), vpaned2);
  gtk_paned_set_position (GTK_PANED (vpaned2), 310);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (window2), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_paned_pack1 (GTK_PANED (vpaned2), scrolledwindow4, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
/**********/
  store1 = gtk_list_store_new(3,G_TYPE_STRING,G_TYPE_STRING,G_TYPE_STRING);
  gtk_object_set_data_full(GTK_OBJECT (window2),"store1",store1,NULL);
  list1 = gtk_tree_view_new_with_model(GTK_TREE_MODEL(store1));
  select = gtk_tree_view_get_selection(GTK_TREE_VIEW(list1));
  gtk_tree_selection_set_mode(select,GTK_SELECTION_SINGLE);

  renderer = gtk_cell_renderer_text_new();
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list1),0,"Type",renderer,"text",0,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list1),1,"Name",renderer,"text",1,NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(list1),2,"Size",renderer,"text",2,NULL);
  gtk_tree_view_set_headers_clickable(GTK_TREE_VIEW(list1),TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list1),0);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,45);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list1),1);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,316);
  gtk_tree_view_column_set_resizable(column,TRUE);
  column = gtk_tree_view_get_column(GTK_TREE_VIEW(list1),2);
  gtk_tree_view_column_set_sizing(column,GTK_TREE_VIEW_COLUMN_FIXED);
  gtk_tree_view_column_set_fixed_width(column,80);
  gtk_tree_view_column_set_resizable(column,TRUE);

  gtk_widget_ref(list1);
  gtk_object_set_data_full(GTK_OBJECT(window2),"list1",list1,(GtkDestroyNotify)gtk_widget_unref);
  gtk_widget_show(list1);
  gtk_container_add(GTK_CONTAINER(scrolledwindow4),list1);
/**********/
  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (window2), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_paned_pack2 (GTK_PANED (vpaned2), vbox2, FALSE, TRUE);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (window2), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 6);

  button5 = gtk_button_new_with_label (_("Download"));
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (window2), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);
  gtk_box_pack_start (GTK_BOX (hbox1), button5, FALSE, FALSE, 0);
  gtk_widget_set_usize (button5, 70, 20);

  button6 = gtk_button_new_with_label (_("Close"));
  gtk_widget_ref (button6);
  gtk_object_set_data_full (GTK_OBJECT (window2), "button6", button6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button6);
  gtk_box_pack_start (GTK_BOX (hbox1), button6, FALSE, FALSE, 0);
  gtk_widget_set_usize (button6, 70, 20);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_ref (statusbar1);
  gtk_object_set_data_full (GTK_OBJECT (window2), "statusbar1", statusbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox2), statusbar1, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (window2), "delete_event",
                      GTK_SIGNAL_FUNC (on_window2_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (list1), "button_press_event",
                      GTK_SIGNAL_FUNC (on_list1_button_press_event),
                      (gpointer)window2);
  gtk_signal_connect (GTK_OBJECT (button5), "clicked",
                      GTK_SIGNAL_FUNC (on_button5_clicked),
                      (gpointer)window2);
  gtk_signal_connect (GTK_OBJECT (button6), "clicked",
                      GTK_SIGNAL_FUNC (on_button6_clicked),
                      (gpointer)window2);

  return window2;
}

GtkWidget*
create_fileselection1 (void)
{
  GtkWidget *fileselection1;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;

  fileselection1 = gtk_file_selection_new (_("Save file as..."));
  gtk_object_set_data (GTK_OBJECT (fileselection1), "fileselection1", fileselection1);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection1), 10);
  gtk_window_set_position (GTK_WINDOW (fileselection1), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (fileselection1), TRUE);

  ok_button1 = GTK_FILE_SELECTION (fileselection1)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection1), "ok_button1", ok_button1);
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_FILE_SELECTION (fileselection1)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection1), "cancel_button1", cancel_button1);
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (ok_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button1_clicked),
                      (gpointer)fileselection1);
  gtk_signal_connect (GTK_OBJECT (cancel_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button1_clicked),
                      (gpointer)fileselection1);

  return fileselection1;
}

GtkWidget*
create_fileselection2 (void)
{
  GtkWidget *fileselection2;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;

  fileselection2 = gtk_file_selection_new (_("Save directory as ..."));
  gtk_object_set_data (GTK_OBJECT (fileselection2), "fileselection2", fileselection2);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection2), 10);
  gtk_window_set_position (GTK_WINDOW (fileselection2), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (fileselection2), TRUE);

  ok_button2 = GTK_FILE_SELECTION (fileselection2)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection2), "ok_button2", ok_button2);
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);

  cancel_button2 = GTK_FILE_SELECTION (fileselection2)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection2), "cancel_button2", cancel_button2);
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (ok_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button2_clicked),
                      (gpointer)fileselection2);
  gtk_signal_connect (GTK_OBJECT (cancel_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button2_clicked),
                      (gpointer)fileselection2);

  return fileselection2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *vbox3;
  GtkWidget *label29;
  GtkWidget *hbox3;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *button9;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window3), "window3", window3);
  gtk_widget_set_usize (window3, 400, 200);
  gtk_window_set_title (GTK_WINDOW (window3), _("Different file size... what should I do ?"));
  gtk_window_set_position (GTK_WINDOW (window3), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (window3), TRUE);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (window3), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (window3), vbox3);

  label29 = gtk_label_new ("");
  gtk_widget_ref (label29);
  gtk_object_set_data_full (GTK_OBJECT (window3), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (vbox3), label29, FALSE, FALSE, 0);
  gtk_widget_set_usize (label29, -2, 150);
  gtk_label_set_line_wrap (GTK_LABEL (label29), TRUE);

  hbox3 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (window3), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox3), 12);

  button7 = gtk_button_new_with_label (_("Resume"));
  gtk_widget_ref (button7);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button7", button7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button7);
  gtk_box_pack_start (GTK_BOX (hbox3), button7, FALSE, FALSE, 0);
  gtk_widget_set_usize (button7, 70, -2);

  button8 = gtk_button_new_with_label (_("Overwrite"));
  gtk_widget_ref (button8);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button8", button8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button8);
  gtk_box_pack_start (GTK_BOX (hbox3), button8, FALSE, FALSE, 0);
  gtk_widget_set_usize (button8, 70, -2);

  button9 = gtk_button_new_with_label (_("Ignore"));
  gtk_widget_ref (button9);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button9", button9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button9);
  gtk_box_pack_start (GTK_BOX (hbox3), button9, FALSE, FALSE, 0);
  gtk_widget_set_usize (button9, 70, -2);

  gtk_signal_connect (GTK_OBJECT (button7), "clicked",
                      GTK_SIGNAL_FUNC (on_button7_clicked),
                      (gpointer)window3);
  gtk_signal_connect (GTK_OBJECT (button8), "clicked",
                      GTK_SIGNAL_FUNC (on_button8_clicked),
                      (gpointer)window3);
  gtk_signal_connect (GTK_OBJECT (button9), "clicked",
                      GTK_SIGNAL_FUNC (on_button9_clicked),
                      (gpointer)window3);

  return window3;
}

  GtkTreeModel *store;
  GtkTreeSelection *select;
  GtkTreeView *view;
